import { AuthRouter } from '@/core/auth/context';
import { PropsWithChildren } from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function SubscriptionLayout({ children }: PropsWithChildren) {
  return <AuthRouter allowRedirect>{children}</AuthRouter>;
}
