import { PropsWithChildren } from 'react';
import { PayProvider } from './pay-context';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function SubscriptionLayout({ children }: PropsWithChildren) {
  return <PayProvider>{children}</PayProvider>;
}
