import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { NetworkProvider } from '@/core/network/context';
import { ConfigProvider } from '@/core/config/context';
import { getBuildConfig } from '@/core/config/build-config';

import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const config = getBuildConfig();
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0 }}>
        <ConfigProvider {...config}>
          <NetworkProvider>{children}</NetworkProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
